apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  serviceName: redis   
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        command:
        - redis-server
        - "/redis-master/redis.conf"
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
